home = /home/ys/Code/BooksAndLearning/DataStructures/LinkedList/
make:
	gcc -o linkedList linkedList.c -Wextra -Wall -Wfloat-equal

uncrustify:
	find $(home) -type f -name '*.c' -exec uncrustify --no-backup -l=C {} + 

